### ISSUE TITLE
Include general.trig and model.trig

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/sk_general#2]
### In future combined files, please include the new files with partly new named graphs here: 
- general.trig containing sk:general and soon some other stuff
- model.trig containing sk:model

**Comment by linxOD** [comment]
please check prefixes in both files:
Bad syntax (Prefix "crm:" not bound) at ^ in:
"...b'ral {\n<https://sk.acdh.oeaw.ac.at/types/appellation/date> a '^b'crm:E55_Type ;\n    rdfs:label "Type: Appellation - Date"@en '..."

**Comment by linxOD** [comment]
in all the data repositories "cidoc" is used as a prefix.

**Comment by BOberreither** [comment]
Ahem - fixed in general.trig ...

**Comment by linxOD** [comment]
will be included in combined graphs
