### ISSUE TITLE
model and general named graphs in fackel mention trig

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/sk_general#3]
The model and general named graphs are currently in fackel mention trig.

(Edit: Also, they are added to the other trig files, like LK.)
(2nd edit: Is it because of the inverse triples? To put them into the right named graph? If so, forget issue.)

**Comment by linxOD** [comment]
when inverse triples are created the model and general graph is also added to each created file. We could reduce it to one specific file in each repository or seperate it completely?

**Comment by BOberreither** [comment]
No, seems fine the way it is. Just that the trig files get a little bigger this way. So maybe if file size continues to be a problem, separate them into different files.
